### ISSUE TITLE
Uncaught TypeError: service.register is not a function

### ISSUE THREAD

**Issue by molovo** [Gert-dev/php-integrator-linter#23]
[Enter steps to reproduce below:]

1. Open a PHP file

**Atom Version**: 1.7.0-beta0
**System**: Mac OS X 10.11.3
**Thrown From**: [php-integrator-linter](https://github.com/Gert-dev/php-integrator-linter) package, v0.2.1

### Stack Trace

Uncaught TypeError: service.register is not a function

```
At /Users/molovo/.zprezto/runcoms/.atom/packages/php-integrator-linter/lib/Main.coffee:108

TypeError: service.register is not a function
    at Object.module.exports.setLinterIndieService (/Users/molovo/.zprezto/runcoms/.atom/packages/php-integrator-linter/lib/Main.coffee:108:43)
    at Provider.module.exports.Provider.provide (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs",
      "language-gfm",
      "formatter",
      "formatter-coffeescript"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "node_modules",
      "._*",
      "Thumbs.db",
      ".tags*"
    ],
    "packagesWithKeymapsDisabled": [
      "git-projects",
      "color-picker"
    ],
    "projectHome": "/usr/local/var/www",
    "themes": [
      "spacegray-dark-neue-ui",
      "subway-copenhagen"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
aligner, v0.19.1
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-ruby, v1.4.0
aligner-scss, v1.1.0
atom-alignment, v0.12.1
atom-jade, v0.3.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
battery-status, v0.11.0
codeception-snippets, v0.1.0
docblockr, v0.7.3
emmet, v2.4.2
file-icons, v1.6.18
imdone-atom, v1.3.29
imdone-atom-github, v0.1.9
language-markdown, v0.11.0
line-count-status, v0.0.3
linter, v1.11.4
linter-alex, v2.0.0
linter-coffee-variables, v0.5.0
linter-coffeelint, v1.1.2
linter-htmlhint, v1.1.0
linter-jade, v0.3.2
linter-jsonlint, v1.2.1
linter-just-say-no, v0.6.1
linter-package-json-validator, v1.0.1
linter-phpmd, v1.4.1
linter-proselint, v3.0.0
linter-sass-lint, v1.2.0
linter-write-good, v0.6.1
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
minimap-selection, v4.4.0
minimap-split-diff, v0.3.0
package-cop, v0.2.10
package-sync, v1.0.0
php-cs-fixer, v2.5.6
php-getters-setters, v0.5.5
php-integrator-annotations, v0.3.2
php-integrator-autocomplete-plus, v0.6.0
php-integrator-base, v0.7.2
php-integrator-call-tips, v0.2.2
php-integrator-linter, v0.2.1
php-integrator-navigation, v0.6.1
php-integrator-refactoring, v0.4.0
php-integrator-tooltips, v0.5.0
pigments, v0.24.5
project-manager, v2.7.6
pull-requests, v0.0.19
smart-tags, v0.1.0
spacegray-dark-neue-ui, v1.4.0
subway-copenhagen, v1.0.9
synced-sidebar, v0.4.3
travis-ci-status, v1.0.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by molovo** [comment]
Issue seems to have been caused by the [atom-pull-requests](https://github.com/philschatz/atom-pull-requests/issues/9) package. Uninstalling that stopped the linter from throwing the error.
